<?php

namespace app\components\zalo\services;

use yii\base\BaseObject;
use yii\httpclient\Client;
use yii\web\Request;

class  ZaloNotificationService extends BaseObject
{
    /**
     * @var Client $httpclient ;
     */
    public $httpclient;
    public $accessToken;
    protected $apiTemplate = "https://business.openapi.zalo.me/template/all";
    protected $apiTemplateType = "https://business.openapi.zalo.me/message/template-tag";

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function getTemplate()
    {
        $result = $this->httpclient->get($this->apiTemplate . "?offset=0&limit=10")->addHeaders([
            "access_token" => $this->accessToken
        ])->send();
        return $result->getContent();
    }

    public function getTemplateType()
    {
        $result = $this->httpclient->get($this->apiTemplateType)->addHeaders([
            "access_token" => $this->accessToken
        ])->send();
        return json_decode($result->getContent());
    }
}